# Generated by Django 4.2.7 on 2023-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
